name: Generate Release Documentation

on:
  push:
    tags:
      - 'tvapp/v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate release document
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOKEN_GITHUB_PUBLISH: ${{ secrets.TOKEN_GITHUB_PUBLISH }}
          REPO_NAME: televisa-univision/web-release-integration
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python release_ai_dashboard/run_release.py tvapp/v1.108.0

      - name: Upload generated document
        uses: actions/upload-artifact@v4
        with:
          name: release-doc
          path: release_ai_dashboard/releases/*.docx
